export { IntercomHideDirective } from './directives/hide.directive';
export { IntercomShowMessagesDirective } from './directives/show-messages.directive';
export { IntercomShowNewMessageDirective } from './directives/show-new-message.directive';
export { IntercomShowDirective } from './directives/show.directive';
export { IntercomShutdownDirective } from './directives/shutdown.directive';
export { IntercomTrackEventDirective } from './directives/track-event.directive';
export { IntercomModule } from './intercom.module';
export { Intercom } from './providers/intercom';
export { IntercomConfig } from './types/intercom-config';